

#ifndef H264_CHANNEL_HEADFILE
#define H264_CHANNEL_HEADFILE


#define EXTCHLOFFSET 2

#ifdef CHIP_DM6467
#define CHLOFFSET_H 12
#else
#define CHLOFFSET_H 7
#endif

#define RLDOFFSET 0

#define REFMBCHL    (CHL12_DSP)

#define REFFRAMERLDPARAM0 (0+RLDOFFSET)
#define REFFRAMERLDPARAM1 (1+RLDOFFSET)
#define REFFRAMERLDPARAM2 (2+RLDOFFSET)


#define RECMBROWCHL   (CHL13_DSP)

#define RECMBROWRLDPARAM0 (3+RLDOFFSET)
#define RECMBROWRLDPARAM1 (4+RLDOFFSET)
#define RECMBROWRLDPARAM2 (5+RLDOFFSET)

#define REC421MBROWCHL   (CHL14_DSP)

#define REC421MBROWRLDPARAM0 (6+RLDOFFSET)
#define REC421MBROWRLDPARAM1 (7+RLDOFFSET)
#define REC421MBROWRLDPARAM2 (8+RLDOFFSET)

#define FLTTOPROWCHL   (CHL15_DSP)

#define FLTTOPROWRLDPARAM0 (9 +RLDOFFSET)
#define FLTTOPROWRLDPARAM1 (10+RLDOFFSET)
#define FLTTOPROWRLDPARAM2 (11+RLDOFFSET)

//////////////////////////////////////////////////////////////////////////
//扩边界用到的chl_Dsp_Dsp_Dsp
#define EXTENDCHL0 (CHL12_DSP)
#define EXTENDCHL1 (CHL13_DSP)
#define EXTENDCHL2 (CHL19_DSP)
#define EXTENDCHL3 (CHL15_DSP)
#define EXTENDCHL4 (CHL20_DSP)
#define EXTENDCHL5 (CHL17_DSP)
#define EXTENDCHL6 (CHL18_DSP)

#define HANDLE_DMA (CHL21_DSP)

#endif //H264_CHANNEL_HEADFILE

